package com.example.vaadin542;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainLayout extends CssLayout {
    protected VerticalLayout vLayout;
    protected Label lbl1;
    protected Label lbl2;
    protected TextField txtField1;
    protected ComboBox cmbBox1;
    protected Button btnSearch;
    protected ComboBox andOr2;
    protected TextField txtField2;
    protected ComboBox cmbBox2;
    protected Button btnMinus2;
    protected ComboBox andOr3;
    protected TextField txtField3;
    protected ComboBox cmbBox3;
    protected Button btnMinus3;
    protected ComboBox andOr4;
    protected TextField txtField4;
    protected ComboBox cmbBox4;
    protected Button btnMinus4;
    protected Button btnAddSrch;

    public MainLayout() {
        Design.read(this);
    }
}
