package com.example.vaadin542;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MovieSummary extends Panel {
    protected Image imgPoster;
    protected GridLayout btn;
    protected Label lblTitle;
    protected Label lblYear;
    protected Label lblRating;
    protected Label lblBudget;
    protected Label lblRevenue;
    protected Label lblDirector;
    protected Label lblCast;
    protected GridLayout btn2;
    protected Button btnGenre;
    protected Button btnGenre2;
    protected Button btnGenre3;
    protected Button btnGenre4;
    protected Button btnGenre5;
    protected TextArea txtAreaSynopsis;

    public MovieSummary() {
        Design.read(this);
    }
}
